version: '2.2'
services:
  db:
    build: db-petclinic-test
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic

    # defining health-check test. This will be run inside the container.
    # healthy status can be inspected using docker inspect.

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-P","3306","-u","root","-ppetclinic"]
      interval: 5s
      retries: 15
    networks:
    - petclinic-test
  petclinic:
    build: petclinic-jar/
    ports:
    - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
    - db
    networks:
    - petclinic-test

networks:
  petclinic-test:
    driver: bridge
